name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    name: Update this repo's tryhackme badge
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      - uses: ymedlop/tryhackme-badge-workflow@main
        with:
          username: "Wreak1337"
          committer_username: "WreakDev"
          committer_email: "WreakDev@users.noreply.github.com"
          image_path: "./assets/tryhackme.png"
          use_static_image: "false"
          user_public_id: "7168674"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
